dependencies:
    - name: mongodb
      version: "3.0.4"
#     repository: "https://example.com/charts"
      repository: "http://kubernetes-charts.storage.googleapis.com"
      condition: mongodb.enabled
